spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: sdfsdf238ru2938ru92rje
            client-secret: 238oiwejoijsdfr4r
            redirect-uri: 234sdfsdfsdgdfshg
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id